# -*- coding: utf-8 -*-
"""save_word_vecs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14SObtlGgU051ntu0OyIhj82k5JooxFzO
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive/CS6910_PA3/
!pwd

import pickle
with open('./data/word_to_ix.pickle', 'rb') as handle:
    word_to_ix = pickle.load(handle)
with open('./data/ix_to_word.pickle', 'rb') as handle:
    ix_to_word = pickle.load(handle)
vocab_size = len(word_to_ix)

import numpy as np
import torch

def save_to_file(fname, embed):
  with open(fname, 'w+') as f:
    for k in word_to_ix.keys():
      f.write(k+' ')
      np.savetxt(f,embed[word_to_ix[k]],newline=' ',fmt='%1.6f')
      f.write('\n')

from word2vec_models import CBOW, Skipgram

#cbow d100 cs2
model_path = './data/cbow_d100_cs_2_5.pth'
checkpoint = torch.load(f=model_path, map_location=torch.device('cpu'))
net = CBOW(vocab_size, 100, 4)
net.load_state_dict(checkpoint['model_state_dict'])
net.eval()

save_to_file('./data/cbow_d100.txt',net.embeddings.weight.detach().numpy())

#cbow d200 cs2
model_path = './data/cbow_d200_cs_2_5.pth'
checkpoint = torch.load(f=model_path, map_location=torch.device('cpu'))
net = CBOW(vocab_size, 200, 4)
net.load_state_dict(checkpoint['model_state_dict'])
net.eval()

save_to_file('./data/cbow_d200.txt',net.embeddings.weight.detach().numpy())

#skipgram d100 cs2
model_path = './data/skipgram_d100_cs_2_5.pth'
checkpoint = torch.load(f=model_path, map_location=torch.device('cpu'))
net = Skipgram(vocab_size, 100, 2)
net.load_state_dict(checkpoint['model_state_dict'])
net.eval()

save_to_file('./data/skipgram_d100.txt',net.embeddings.weight.detach().numpy())

#skipgram d200 cs2
model_path = './data/skipgram_d200_cs_2_5.pth'
checkpoint = torch.load(f=model_path, map_location=torch.device('cpu'))
net = Skipgram(vocab_size, 200, 2)
net.load_state_dict(checkpoint['model_state_dict'])
net.eval()

save_to_file('./data/skipgram_d200.txt',net.embeddings.weight.detach().numpy())

